-- INS_APP."MEMBER" definition

CREATE TABLE "INS_APP"."MEMBER"
(	"MEMBER_ID" VARCHAR2(32),
     "SITE_ID" VARCHAR2(32),
     "LOGIN_ID" VARCHAR2(50) NOT NULL ENABLE,
     "PASSWORD" VARCHAR2(255) NOT NULL ENABLE,
     "MEMBER_NAME" VARCHAR2(100) NOT NULL ENABLE,
     "AUTH_LEVEL" VARCHAR2(1),
     "EMAIL" VARCHAR2(200),
     "USE_YN" VARCHAR2(1) DEFAULT 'Y',
     "REG_DT" TIMESTAMP (6) DEFAULT SYSDATE,
     "MOD_DT" TIMESTAMP (6),
     "REG_USER" VARCHAR2(32),
     "DEPT_ID" VARCHAR2(32),
     PRIMARY KEY ("MEMBER_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "INS_DATA"  ENABLE,
     UNIQUE ("LOGIN_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "INS_DATA"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INS_DATA" ;

-- INS_APP.REFRESH_TOKEN definition

CREATE TABLE "INS_APP"."REFRESH_TOKEN"
(	"MEMBER_ID" VARCHAR2(32),
     "TOKEN" VARCHAR2(512) NOT NULL ENABLE,
     "EXPIRES_AT" TIMESTAMP (6) NOT NULL ENABLE,
     "CREATED_AT" TIMESTAMP (6) DEFAULT SYSDATE,
     PRIMARY KEY ("MEMBER_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "INS_DATA"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INS_DATA" ;