# \uC6B4\uC601\uC11C\uBC84 \uD0C0\uC785(WINDOWS, UNIX)
Globals.OsType=WINDOWS

#hsql - local hssql \uC0AC\uC6A9\uC2DC\uC5D0 \uC801\uC6A9 (\uB0B4\uC7A5 hsql\uC740 \uC815\uBCF4 \uD544\uC694 \uC5C6\uC74C)
Globals.oracle.DriverClassName=net.sf.log4jdbc.DriverSpy
Globals.oracle.Url=jdbc:log4jdbc:oracle:thin:@101.55.81.37:1521/ORCL
Globals.oracle.UserName=INS_APP
Globals.oracle.Password=insApp4787@

logging.rollingpolicy.maxHistory=2

# File store Path
Globals.fileStorePath=./files